name: coffeecom-backend
regions:
- fra
services:
  - name: api
    instance_type: nano
    image: docker.io/gonetoer/coffeecom-backend:latest
    ports:
      - port: 5000
        protocol: http
    routes:
      - path: /
        port: 5000
    env:
      - name: FLASK_ENV
        value: production
      - name: SECRET_KEY
        secret: SECRET_KEY
      - name: JWT_SECRET_KEY
        secret: JWT_SECRET_KEY
      - name: SQLALCHEMY_DATABASE_URI
        secret: SQLALCHEMY_DATABASE_URI
      - name: CORS_ORIGINS
        value: "*"
    healthcheck:
      http:
        path: /
        port: 5000
      initial_delay: 10s
      interval: 30s
      timeout: 5s
      retries: 3
