name: Deploy to Koyeb

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/coffeecom-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/coffeecom-backend:latest

      - name: Deploy to Koyeb
        uses: koyeb/action-deploy@v1
        with:
          api-token: ${{ secrets.KOYEB_TOKEN }}
          app-name: coffeecom-backend
          service-name: database
          service-ports: 8000:http
          docker-image: ${{ secrets.DOCKERHUB_USERNAME }}/coffeecom-backend:latest
          service-env: |
            PORT=8000
            FLASK_ENV=production
            SQLALCHEMY_DATABASE_URI=${{ secrets.DATABASE_URL }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}