name: Deploy to Koyeb

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/coffeecom-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/coffeecom-backend:latest

      - name: Deploy on Koyeb
        run: |
          curl -X POST "https://app.koyeb.com/services/eb175cfc-32b4-48f9-b1f6-1806fd62707d?deploymentId=0fed4349-c2ff-470d-9b1b-f3bfcc3db9bf" \
            -H "Authorization: Bearer ${{ secrets.KOYEB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"service": "database", "image": "${{ secrets.DOCKERHUB_USERNAME }}/coffeecom-backend:latest"}'